/**
 * Raw .bm file integration tests.
 *
 * Reads bitmap files generated by util/gen_test_bitmaps.sh
 * (packed bits, little-endian bit order — same format as gen_bitmap.sh).
 *
 * Tests all 3 backends (WAH, CRoaring, ComBit) with real file data:
 *   - Load raw .bm → Append bits → verify Cardinality
 *   - Serialize/Load round-trip
 *   - Logical operations on column bitmaps
 *   - Cross-backend consistency
 *
 * Run:  OUTPUT_DIR=test_bitmaps bash util/gen_test_bitmaps.sh
 *       cd build && cmake .. && make bm_file_tests && ./bm_file_tests
 */
#include <gtest/gtest.h>
#include "benchmark/bitmap_backend.h"
#include "benchmark/backends/wah/wah_backend.h"
#include "benchmark/backends/croaring/croaring_backend.h"
#include "benchmark/backends/combit/combit_backend.h"
#include "benchmark/backends/ewah/ewah_backend.h"

#include <filesystem>
#include <fstream>
#include <map>
#include <set>
#include <vector>
#include <memory>
#include <sstream>
#include <algorithm>

namespace fs = std::filesystem;

// ===================================================================
// Utilities
// ===================================================================

/// Read a raw .bm file (packed bits, little-endian bit order) and return
/// the individual bit values up to `num_rows`.
static std::vector<bool> read_raw_bm(const std::string& path, size_t num_rows) {
    std::ifstream f(path, std::ios::binary);
    EXPECT_TRUE(f.good()) << "Cannot open " << path;
    std::vector<uint8_t> bytes((std::istreambuf_iterator<char>(f)),
                                std::istreambuf_iterator<char>());
    std::vector<bool> bits;
    bits.reserve(num_rows);
    for (size_t byte_idx = 0; byte_idx < bytes.size() && bits.size() < num_rows; ++byte_idx) {
        for (int bit = 0; bit < 8 && bits.size() < num_rows; ++bit) {
            bits.push_back((bytes[byte_idx] >> bit) & 1);
        }
    }
    return bits;
}

/// Build a backend bitmap from a bit vector.
static std::unique_ptr<BitmapHandle> bits_to_bitmap(
    IBitmapBackend& be, const std::vector<bool>& bits)
{
    auto h = be.Create();
    for (bool b : bits) be.Append(*h, b);
    return h;
}

/// Parse metadata.txt into a key→value map.
static std::map<std::string, std::string> read_metadata(const std::string& path) {
    std::map<std::string, std::string> m;
    std::ifstream f(path);
    std::string line;
    while (std::getline(f, line)) {
        auto eq = line.find('=');
        if (eq != std::string::npos)
            m[line.substr(0, eq)] = line.substr(eq + 1);
    }
    return m;
}

static std::unique_ptr<IBitmapBackend> make_backend(const std::string& name) {
    if (name == "WAH")      return std::make_unique<WahBackend>();
    if (name == "CRoaring")  return std::make_unique<CroaringBackend>();
    if (name == "ComBit")    return std::make_unique<CombitBackend>();
    if (name == "EWAH")     return std::make_unique<EwahBackend>();
    return nullptr;
}

// ===================================================================
// Locate test_bitmaps directory
// ===================================================================

/// Return path to test_bitmaps/ directory, searching common locations.
static std::string find_bm_dir() {
    // Check BM_TEST_DIR env first
    const char* env = std::getenv("BM_TEST_DIR");
    if (env && fs::is_directory(env)) return env;

    // Search relative to executable / source tree
    for (auto& candidate : {
        "test_bitmaps",
        "../test_bitmaps",
        "../../test_bitmaps",
    }) {
        if (fs::is_directory(candidate)) return candidate;
    }
    return "";
}

// ===================================================================
// Parameterized fixture: test each backend with .bm files
// ===================================================================
class BmFileTest : public ::testing::TestWithParam<std::string> {
protected:
    std::unique_ptr<IBitmapBackend> backend;
    std::string bm_dir;
    std::map<std::string, std::string> meta;
    size_t num_rows = 0;
    std::string tmp_dir;

    void SetUp() override {
        backend = make_backend(GetParam());
        ASSERT_NE(backend, nullptr);

        bm_dir = find_bm_dir();
        ASSERT_FALSE(bm_dir.empty())
            << "test_bitmaps/ not found. Run: OUTPUT_DIR=test_bitmaps bash util/gen_test_bitmaps.sh";

        meta = read_metadata(bm_dir + "/metadata.txt");
        ASSERT_TRUE(meta.count("num_rows"));
        num_rows = std::stoul(meta["num_rows"]);

        tmp_dir = (fs::temp_directory_path() / ("bm_file_test_" + GetParam())).string();
        fs::create_directories(tmp_dir);
    }

    void TearDown() override {
        fs::remove_all(tmp_dir);
    }

    /// Load a raw .bm file and build a backend bitmap.
    std::unique_ptr<BitmapHandle> load_raw(const std::string& filename) {
        auto bits = read_raw_bm(bm_dir + "/" + filename, num_rows);
        return bits_to_bitmap(*backend, bits);
    }

    uint64_t expected_popcount(const std::string& key) {
        auto it = meta.find(key);
        EXPECT_TRUE(it != meta.end()) << "Missing metadata key: " << key;
        return std::stoull(it->second);
    }
};

INSTANTIATE_TEST_SUITE_P(
    AllBackends, BmFileTest,
    ::testing::Values("WAH", "CRoaring", "ComBit", "EWAH"),
    [](const ::testing::TestParamInfo<std::string>& info) { return info.param; }
);

// ======================== Cardinality verification ========================

TEST_P(BmFileTest, AllZerosCardinality) {
    auto bm = load_raw("all_zeros.bm");
    EXPECT_EQ(backend->Cardinality(*bm), 0u);
}

TEST_P(BmFileTest, AllOnesCardinality) {
    auto bm = load_raw("all_ones.bm");
    EXPECT_EQ(backend->Cardinality(*bm), expected_popcount("all_ones_popcount"));
}

TEST_P(BmFileTest, SingleBitCardinality) {
    auto bm = load_raw("single_bit_500.bm");
    EXPECT_EQ(backend->Cardinality(*bm), 1u);
    auto decoded = backend->Decode(*bm);
    ASSERT_EQ(decoded.size(), 1u);
    EXPECT_EQ(decoded[0], 500u);
}

TEST_P(BmFileTest, AlternatingCardinality) {
    auto bm = load_raw("alternating.bm");
    EXPECT_EQ(backend->Cardinality(*bm), expected_popcount("alternating_popcount"));
}

TEST_P(BmFileTest, SparseCardinality) {
    auto bm = load_raw("sparse_1pct.bm");
    EXPECT_EQ(backend->Cardinality(*bm), expected_popcount("sparse_1pct_popcount"));
}

TEST_P(BmFileTest, DenseCardinality) {
    auto bm = load_raw("dense_90pct.bm");
    EXPECT_EQ(backend->Cardinality(*bm), expected_popcount("dense_90pct_popcount"));
}

// ======================== Column bitmaps ========================

TEST_P(BmFileTest, ColumnCardinalitySumEqualsNumRows) {
    // Sum of all column value popcounts should equal num_rows
    uint64_t total = 0;
    for (int val = 1; val <= 5; ++val) {
        auto bm = load_raw("column/" + std::to_string(val) + ".bm");
        total += backend->Cardinality(*bm);
    }
    EXPECT_EQ(total, num_rows);
}

TEST_P(BmFileTest, ColumnValuesAreMutuallyExclusive) {
    // AND of any two different column bitmaps should be empty
    auto bm1 = load_raw("column/1.bm");
    auto bm2 = load_raw("column/2.bm");
    auto result = backend->bitAnd(*bm1, *bm2);
    EXPECT_EQ(backend->Cardinality(*result), 0u);
}

TEST_P(BmFileTest, ColumnORAllEqualsAllOnes) {
    // OR of all 5 column bitmaps should have cardinality == num_rows
    auto acc = load_raw("column/1.bm");
    for (int val = 2; val <= 5; ++val) {
        auto bm = load_raw("column/" + std::to_string(val) + ".bm");
        acc = backend->bitOr(*acc, *bm);
    }
    EXPECT_EQ(backend->Cardinality(*acc), num_rows);
}

TEST_P(BmFileTest, ColumnIndividualPopcounts) {
    for (int val = 1; val <= 5; ++val) {
        auto bm = load_raw("column/" + std::to_string(val) + ".bm");
        std::string key = "column_" + std::to_string(val) + "_popcount";
        EXPECT_EQ(backend->Cardinality(*bm), expected_popcount(key))
            << "column value " << val;
    }
}

// ======================== Logical operations on .bm data ========================

TEST_P(BmFileTest, OrAllZerosIsIdentity) {
    auto zeros = load_raw("all_zeros.bm");
    auto sparse = load_raw("sparse_1pct.bm");
    auto result = backend->bitOr(*zeros, *sparse);
    EXPECT_EQ(backend->Cardinality(*result),
              expected_popcount("sparse_1pct_popcount"));
}

TEST_P(BmFileTest, AndAllOnesIsIdentity) {
    auto ones = load_raw("all_ones.bm");
    auto sparse = load_raw("sparse_1pct.bm");
    auto result = backend->bitAnd(*ones, *sparse);
    EXPECT_EQ(backend->Cardinality(*result),
              expected_popcount("sparse_1pct_popcount"));
}

TEST_P(BmFileTest, AndAllZerosIsEmpty) {
    auto zeros = load_raw("all_zeros.bm");
    auto dense = load_raw("dense_90pct.bm");
    auto result = backend->bitAnd(*zeros, *dense);
    EXPECT_EQ(backend->Cardinality(*result), 0u);
}

TEST_P(BmFileTest, XorSelfIsZero) {
    auto alt = load_raw("alternating.bm");
    auto result = backend->bitXor(*alt, *alt);
    EXPECT_EQ(backend->Cardinality(*result), 0u);
}

TEST_P(BmFileTest, OrSelfIsSelf) {
    auto dense = load_raw("dense_90pct.bm");
    auto result = backend->bitOr(*dense, *dense);
    EXPECT_EQ(backend->Cardinality(*result),
              expected_popcount("dense_90pct_popcount"));
}

// ======================== Decode verification ========================

TEST_P(BmFileTest, DecodeAllZerosIsEmpty) {
    auto bm = load_raw("all_zeros.bm");
    auto decoded = backend->Decode(*bm);
    EXPECT_TRUE(decoded.empty());
}

TEST_P(BmFileTest, DecodeAlternating) {
    auto bm = load_raw("alternating.bm");
    auto decoded = backend->Decode(*bm);
    ASSERT_EQ(decoded.size(), num_rows / 2);
    // Even positions should be absent, odd positions present?
    // alternating = [i % 2 for i in range(n)], so position 0 = 0, position 1 = 1, ...
    for (size_t i = 0; i < decoded.size(); ++i) {
        EXPECT_EQ(decoded[i], 2 * i + 1) << "at index " << i;
    }
}

// ======================== Serialize / Load round-trip ========================

TEST_P(BmFileTest, SerializeLoadRoundTrip) {
    // Build from raw .bm, serialize in backend format, load back, verify
    auto bm = load_raw("dense_90pct.bm");
    auto orig_card = backend->Cardinality(*bm);

    std::string path = tmp_dir + "/dense_rt.bm";
    backend->Serialize(*bm, path);

    auto loaded = backend->Load(path);
    // WAH may add padding; at least the cardinality should be >= original
    auto loaded_card = backend->Cardinality(*loaded);
    if (GetParam() == "WAH") {
        EXPECT_GE(loaded_card, orig_card);
    } else {
        EXPECT_EQ(loaded_card, orig_card);
    }
}

// ======================== Cross-backend consistency ========================

class CrossBackendBmTest : public ::testing::Test {
protected:
    std::string bm_dir;
    size_t num_rows = 0;
    std::map<std::string, std::string> meta;

    void SetUp() override {
        bm_dir = find_bm_dir();
        ASSERT_FALSE(bm_dir.empty());
        meta = read_metadata(bm_dir + "/metadata.txt");
        num_rows = std::stoul(meta["num_rows"]);
    }
};

TEST_F(CrossBackendBmTest, CardinalityConsistentAcrossBackends) {
    // All backends should report the same cardinality for each file
    std::vector<std::string> files = {
        "all_zeros.bm", "all_ones.bm", "sparse_1pct.bm",
        "dense_90pct.bm", "alternating.bm", "single_bit_500.bm"
    };

    for (auto& file : files) {
        auto bits = read_raw_bm(bm_dir + "/" + file, num_rows);
        uint64_t prev_card = 0;
        std::string prev_name;
        for (auto& name : {"WAH", "CRoaring", "ComBit", "EWAH"}) {
            auto be = make_backend(name);
            auto bm = bits_to_bitmap(*be, bits);
            auto card = be->Cardinality(*bm);
            if (!prev_name.empty()) {
                EXPECT_EQ(card, prev_card)
                    << file << ": " << name << " vs " << prev_name;
            }
            prev_card = card;
            prev_name = name;
        }
    }
}

TEST_F(CrossBackendBmTest, LogicalOpResultsConsistent) {
    // OR(sparse, dense) should give same cardinality across all backends
    auto sparse_bits = read_raw_bm(bm_dir + "/sparse_1pct.bm", num_rows);
    auto dense_bits  = read_raw_bm(bm_dir + "/dense_90pct.bm", num_rows);

    uint64_t prev_or = 0, prev_and = 0;
    std::string prev_name;

    for (auto& name : {"WAH", "CRoaring", "ComBit", "EWAH"}) {
        auto be = make_backend(name);
        auto a = bits_to_bitmap(*be, sparse_bits);
        auto b = bits_to_bitmap(*be, dense_bits);

        auto or_res  = be->bitOr(*a, *b);
        auto and_res = be->bitAnd(*a, *b);

        auto or_card  = be->Cardinality(*or_res);
        auto and_card = be->Cardinality(*and_res);

        if (!prev_name.empty()) {
            EXPECT_EQ(or_card, prev_or)
                << "OR: " << name << " vs " << prev_name;
            EXPECT_EQ(and_card, prev_and)
                << "AND: " << name << " vs " << prev_name;
        }
        prev_or = or_card;
        prev_and = and_card;
        prev_name = name;
    }
}

TEST_F(CrossBackendBmTest, DecodeConsistentAcrossBackends) {
    // Decode of single_bit_500 should return {500} for all backends
    auto bits = read_raw_bm(bm_dir + "/single_bit_500.bm", num_rows);
    for (auto& name : {"WAH", "CRoaring", "ComBit", "EWAH"}) {
        auto be = make_backend(name);
        auto bm = bits_to_bitmap(*be, bits);
        auto decoded = be->Decode(*bm);
        ASSERT_EQ(decoded.size(), 1u) << name;
        EXPECT_EQ(decoded[0], 500u) << name;
    }
}
