#!/usr/bin/env python3
"""
Script: verify_bmz.py
Description: Verify .bmz files generated by gen_bitmap.sh against the original dataset.

For each bitmap (value 1..cardinality):
  - Read the original dataset, find all rows where value appears
  - Read the corresponding bitmap from the .bmz file
  - Compare: the two must match exactly

Usage:
    python3 verify_bmz.py [-d dataset_file] [-b bitmap_dir] [-s sample_size]

Options:
    -d  Path to original dataset file (default: ./dataset_10000_10000)
    -b  Path to bitmaps directory     (default: ./bitmaps)
    -s  Number of bitmaps to sample   (default: 10, use 0 to check all)
"""

import os
import sys
import argparse
import random
import numpy as np


def read_index(index_path):
    """Parse index.txt, return dict of parameters and bmz mapping."""
    params = {}
    mapping = {}  # bmz_index -> (start_val, end_val)
    with open(index_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            if '=' in line:
                key, val = line.split('=', 1)
                params[key.strip()] = int(val.strip())
            elif '.bmz:' in line:
                # e.g. "0.bmz: bitmaps 1-100"
                parts = line.split()
                bmz_idx = int(parts[0].replace('.bmz:', ''))
                start_val, end_val = map(int, parts[-1].split('-'))
                mapping[bmz_idx] = (start_val, end_val)
    return params, mapping


def read_bitmap_from_bmz(bmz_path, val, start_val, num_rows, files_per_dir):
    """Read a single bitmap for `val` from a .bmz file."""
    bitmap_size = (num_rows + 7) // 8  # bytes per bitmap
    offset = (val - start_val) * bitmap_size
    with open(bmz_path, 'rb') as f:
        f.seek(offset)
        raw = f.read(bitmap_size)
    data = np.frombuffer(raw, dtype=np.uint8)
    bits = np.unpackbits(data, bitorder='little')
    return bits[:num_rows]


def verify_value(val, dataset, num_rows, bitmap_dir, params, mapping):
    """Verify bitmap for a single value against the dataset."""
    files_per_dir = params['files_per_dir']

    # Find which bmz file contains this value
    bmz_idx = (val - 1) // files_per_dir
    bmz_path = os.path.join(bitmap_dir, f'{bmz_idx}.bmz')
    start_val = mapping[bmz_idx][0]

    if not os.path.isfile(bmz_path):
        print(f"  [SKIP] value {val}: {bmz_idx}.bmz not found")
        return None

    # Ground truth from dataset
    expected = (dataset == val).astype(np.uint8)

    # Read from bmz
    actual = read_bitmap_from_bmz(bmz_path, val, start_val, num_rows, files_per_dir)

    match = np.array_equal(expected, actual)
    status = "PASS" if match else "FAIL"
    popcount_expected = int(expected.sum())
    popcount_actual = int(actual.sum())
    print(f"  [{status}] value={val:5d} | popcount: expected={popcount_expected}, actual={popcount_actual}", end="")
    if not match:
        diff = np.where(expected != actual)[0]
        print(f" | first mismatch at row {diff[0]}", end="")
    print()
    return match


def main():
    parser = argparse.ArgumentParser(description='Verify .bmz files against original dataset.')
    parser.add_argument('-d', '--dataset', default=None, help='Path to dataset file')
    parser.add_argument('-b', '--bitmaps', default='./bitmaps', help='Path to bitmaps directory')
    parser.add_argument('-s', '--sample', type=int, default=10,
                        help='Number of bitmaps to sample (0 = all)')
    args = parser.parse_args()

    bitmap_dir = args.bitmaps
    index_path = os.path.join(bitmap_dir, 'index.txt')

    # Read index
    if not os.path.isfile(index_path):
        print(f"Error: index.txt not found in {bitmap_dir}")
        sys.exit(1)

    params, mapping = read_index(index_path)
    num_rows = params['rows']
    cardinality = params['cardinality']

    # Auto-detect dataset file if not specified
    dataset_path = args.dataset
    if dataset_path is None:
        dataset_path = f'./dataset_{num_rows}_{cardinality}'
    if not os.path.isfile(dataset_path):
        print(f"Error: dataset file not found: {dataset_path}")
        sys.exit(1)

    print(f"Dataset:    {dataset_path}")
    print(f"Bitmaps:    {bitmap_dir}")
    print(f"rows={num_rows}, cardinality={cardinality}, files_per_dir={params['files_per_dir']}")

    # Load dataset
    print(f"\nLoading dataset...")
    dataset = np.fromfile(dataset_path, dtype=np.int32)
    if len(dataset) != num_rows:
        print(f"Error: dataset has {len(dataset)} rows, expected {num_rows}")
        sys.exit(1)
    print(f"Dataset loaded: {len(dataset)} rows")

    # Determine which values to check
    all_vals = list(range(1, cardinality + 1))
    if args.sample == 0:
        check_vals = all_vals
        print(f"\nChecking all {cardinality} bitmaps...")
    else:
        random.seed(42)
        check_vals = sorted(random.sample(all_vals, min(args.sample, cardinality)))
        print(f"\nSampling {len(check_vals)} bitmaps: {check_vals}")

    print("=" * 60)

    passed = 0
    failed = 0
    for val in check_vals:
        result = verify_value(val, dataset, num_rows, bitmap_dir, params, mapping)
        if result is True:
            passed += 1
        elif result is False:
            failed += 1

    print("=" * 60)
    print(f"Results: {passed} passed, {failed} failed")
    if failed == 0:
        print("All checks passed!")
    else:
        print("Some checks failed.")
    sys.exit(0 if failed == 0 else 1)


if __name__ == '__main__':
    main()