#!/usr/bin/env python3
"""
Script: verify_bmz.py
Description: Verify bitmap files (.bm or .bmz) generated by gen_bitmap.sh
             against the original dataset.

Usage:
    python3 verify_bmz.py -b <bitmap_dir> [-d <dataset_file>] [-s <sample_size>]

Options:
    -b  Path to bitmap directory, e.g. ./bitmap_n10000_c10000_z100
    -d  Path to original dataset file (auto-detected from index.txt if not specified)
    -s  Number of bitmaps to sample (default: 10, use 0 to check all)
"""

import os
import sys
import argparse
import random
import numpy as np


def read_index(index_path):
    """Parse index.txt, return params dict."""
    params = {}
    with open(index_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            if '=' in line and not line.startswith('value'):
                key, val = line.split('=', 1)
                key = key.strip()
                val = val.strip()
                try:
                    params[key] = int(val)
                except ValueError:
                    pass
    return params


def read_bm_file(bm_path, num_rows):
    """Read a single .bm file and return bit array of length num_rows."""
    data = np.fromfile(bm_path, dtype=np.uint8)
    bits = np.unpackbits(data, bitorder='little')
    return bits[:num_rows]


def read_bitmap_from_bmz(bmz_path, val, start_val, packed_bytes, num_rows):
    """Read a single bitmap for `val` from a .bmz file using byte offset."""
    offset = (val - start_val) * packed_bytes
    with open(bmz_path, 'rb') as f:
        f.seek(offset)
        raw = f.read(packed_bytes)
    data = np.frombuffer(raw, dtype=np.uint8)
    bits = np.unpackbits(data, bitorder='little')
    return bits[:num_rows]


def verify_value(val, dataset, num_rows, bitmap_dir, params):
    """Verify bitmap for a single value against the dataset."""
    z = params['zip_length']
    packed_bytes = params['packed_bytes_per_bitmap']

    # Ground truth
    expected = (dataset == val).astype(np.uint8)

    if z == 1:
        # .bm mode: individual file
        bm_path = os.path.join(bitmap_dir, f'{val}.bm')
        if not os.path.isfile(bm_path):
            print(f"  [SKIP] value={val}: {val}.bm not found")
            return None
        actual = read_bm_file(bm_path, num_rows)
    else:
        # .bmz mode: merged file
        bmz_idx = (val - 1) // z
        bmz_path = os.path.join(bitmap_dir, f'{bmz_idx}.bmz')
        start_val = bmz_idx * z + 1
        if not os.path.isfile(bmz_path):
            print(f"  [SKIP] value={val}: {bmz_idx}.bmz not found")
            return None
        actual = read_bitmap_from_bmz(bmz_path, val, start_val, packed_bytes, num_rows)

    match = np.array_equal(expected, actual)
    status = "PASS" if match else "FAIL"
    popcount_expected = int(expected.sum())
    popcount_actual = int(actual.sum())
    print(f"  [{status}] value={val:6d} | popcount: expected={popcount_expected}, actual={popcount_actual}", end="")
    if not match:
        diff = np.where(expected != actual)[0]
        print(f" | first mismatch at row {diff[0]}", end="")
    print()
    return match


def main():
    parser = argparse.ArgumentParser(description='Verify bitmap files against original dataset.')
    parser.add_argument('-b', '--bitmaps', required=True, help='Path to bitmap directory')
    parser.add_argument('-d', '--dataset', default=None, help='Path to dataset file')
    parser.add_argument('-s', '--sample', type=int, default=10,
                        help='Number of bitmaps to sample (0 = all)')
    args = parser.parse_args()

    bitmap_dir = args.bitmaps
    done_path = os.path.join(bitmap_dir, 'done.txt')

    if not os.path.isdir(bitmap_dir):
        print(f"Error: Bitmap directory not found: {bitmap_dir}")
        sys.exit(1)
    if not os.path.isfile(done_path):
        print(f"Error: done.txt not found in {bitmap_dir}")
        sys.exit(1)

    params = read_index(done_path)
    num_rows = params['rows']
    cardinality = params['cardinality']
    z = params['zip_length']

    # Auto-detect dataset file
    dataset_path = args.dataset
    if dataset_path is None:
        base_dir = os.path.dirname(os.path.abspath(bitmap_dir))
        dataset_path = os.path.join(base_dir, f'dataset_{num_rows}_{cardinality}')
    if not os.path.isfile(dataset_path):
        print(f"Error: dataset file not found: {dataset_path}")
        sys.exit(1)

    print(f"Dataset:    {dataset_path}")
    print(f"Bitmaps:    {bitmap_dir}")
    print(f"Mode:       {'individual .bm' if z == 1 else f'merged .bmz (zip_length={z})'}")
    print(f"rows={num_rows}, cardinality={cardinality}, zip_length={z}")
    print(f"packed_bytes_per_bitmap={params['packed_bytes_per_bitmap']}")

    # Load dataset
    print(f"\nLoading dataset...")
    dataset = np.fromfile(dataset_path, dtype=np.int32)
    if len(dataset) != num_rows:
        print(f"Error: dataset has {len(dataset)} rows, expected {num_rows}")
        sys.exit(1)
    print(f"Dataset loaded: {len(dataset)} rows")

    # Determine which values to check
    all_vals = list(range(1, cardinality + 1))
    if args.sample == 0:
        check_vals = all_vals
        print(f"\nChecking all {cardinality} bitmaps...")
    else:
        random.seed(42)
        check_vals = sorted(random.sample(all_vals, min(args.sample, cardinality)))
        print(f"\nSampling {len(check_vals)} bitmaps: {check_vals}")

    print("=" * 60)

    passed = 0
    failed = 0
    for val in check_vals:
        result = verify_value(val, dataset, num_rows, bitmap_dir, params)
        if result is True:
            passed += 1
        elif result is False:
            failed += 1

    print("=" * 60)
    print(f"Results: {passed} passed, {failed} failed")
    if failed == 0:
        print("All checks passed!")
    else:
        print("Some checks failed.")
    sys.exit(0 if failed == 0 else 1)


if __name__ == '__main__':
    main()