#!/usr/bin/env python3
"""plot_hierarchy_depth_size.py — stacked-bar PDFs for the L2/L3/L4/L5
marker-depth size study (chart (a) at density 10% / c=10, chart (b) at
density 0.05% / c=2000).

Each bar = one variant.  Bar segments (bottom → top): L1, L2, L3, L4, L5.
The L2/L3/L4 variants have only their corresponding lower layers, so the
top stacks are absent.

Colour + pattern convention mirrors the TPC-H speedup chart
(eva/graphs_DuckDB/tpch_speedup.gnuplot):
  - L1: solid dark grey (no pattern)            #5D5D5D
  - L2: pattern 4 (dense diagonal /)            #A84141   red
  - L3: pattern 6 (cross hatch +)               #33807F   teal
  - L4: pattern 2 (diagonal /)                  #643D83   purple
  - L5: pattern 7 (diagonal \\)                  #C57A21   amber
"""

from __future__ import annotations
import csv
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

LAYER_STYLE = [
    # (label,        column, gnuplot fill,           colour    )
    ("L1",           2,      "fill solid 1.0",       "#5D5D5D"),
    ("L2",           3,      "fill pattern 4",       "#A84141"),
    ("L3",           4,      "fill pattern 6",       "#33807F"),
    ("L4",           5,      "fill pattern 2",       "#643D83"),
    ("L5",           6,      "fill pattern 7",       "#C57A21"),
]

def load_csv():
    rows = {}     # rows[(c, variant)] = (l1, l2, l3, l4, l5, total_MiB)
    with (HERE / "bench_L_sizes.csv").open() as f:
        for r in csv.DictReader(f):
            c = int(r["cardinality"])
            v = r["variant"]
            l1 = float(r["l1_bytes"]) / (1024 * 1024)
            l2 = float(r["l2_bytes"]) / (1024 * 1024)
            l3 = float(r["l3_bytes"]) / (1024 * 1024)
            l4 = float(r["l4_bytes"]) / (1024 * 1024)
            l5 = float(r["l5_bytes"]) / (1024 * 1024)
            total = float(r["total_MiB"])
            rows[(c, v)] = (l1, l2, l3, l4, l5, total)
    return rows


def write_dat(rows, c, dat_path: Path):
    """Write a 4-row data file (one row per variant)."""
    with dat_path.open("w") as f:
        f.write("# variant\tL1\tL2\tL3\tL4\tL5\ttotal\n")
        for v in ["L2", "L3", "L4", "L5"]:
            l1, l2, l3, l4, l5, total = rows[(c, v)]
            f.write(f"{v}\t{l1:.4f}\t{l2:.4f}\t{l3:.4f}\t{l4:.4f}\t{l5:.4f}\t{total:.4f}\n")


def y_axis_settings(rows, c):
    """Choose y-axis range + tics so the chart looks readable."""
    if c == 10:
        return (0, 100, "0,20,100", "Compressed bitvector size (MB)")
    else:  # c == 2000 — broken Y axis at ~470, label 3075 above the cut
        return (0, 780, "0,200,600", "Compressed bitvector size (MB)")


def write_gp(c, dat_path: Path, pdf_path: Path, rows):
    """Standard rowstacked histogram for c=10."""
    ymin, ymax, ytics_spec, ylabel = y_axis_settings(rows, c)
    plot_lines = []
    for i, (label, col, fill, colour) in enumerate(LAYER_STYLE):
        if i == 0:
            plot_lines.append(
                f"     '{dat_path.name}' using {col}:xtic(1) "
                f"title '{label}' lc rgb '{colour}' {fill} border lc rgb '{colour}'"
            )
        else:
            plot_lines.append(
                f"     ''                 using {col}             "
                f"title '{label}' lc rgb '{colour}' {fill} border lc rgb '{colour}'"
            )
    label_y_off = ymax * 0.025
    plot_lines.append(
        f"     ''                 using ($0):($7+{label_y_off:.3f}):"
        f"(sprintf('%.1f', $7)) notitle "
        f"with labels center font 'Linux Libertine O,18' textcolor rgb '#202020'"
    )
    plot_clause = ", \\\n".join(plot_lines)
    script = f"""# auto-generated by plot_hierarchy_depth_size.py
reset
set terminal pdf size 4.2, 3.0 font 'Linux Libertine O,18'
set output '{pdf_path.name}'

set ylabel '{ylabel}' offset 1.5,0 font 'Linux Libertine O,18'
set yrange [{ymin}:{ymax}]
set ytics {ytics_spec} font 'Linux Libertine O,16'
set xtics offset 0,0.3 font 'Linux Libertine O,18'
set xtics scale 0

set key at graph 0.99, 0.99 right top vertical Left reverse \\
    samplen 1.5 spacing 1.0 width -1 \\
    font 'Linux Libertine O,14'

set style data histogram
set style histogram rowstacked
set style fill pattern border
set boxwidth 0.45
set xrange [-0.6:3.6]

set lmargin 7.0
set rmargin 0.7
set tmargin 0.6
set bmargin 2.2

set border lw 1.2 lc rgb '#0f172a'
set tics nomirror

plot \\
{plot_clause}
"""
    pdf_path.with_suffix(".gp").write_text(script)


def write_gp_with_break(c, dat_path: Path, pdf_path: Path, rows):
    """Special version for chart (b) at c=2000 where the L2 variant
    towers (3075 MB) over the others (~320-560 MB).  Mirrors the
    lightning-break pattern from tpch_speedup.gnuplot:
      - histogram only plots L3 / L4 / L5 bars (L2 row in dat is zero)
      - L2 bar is drawn manually as polygons:
          * L1 segment   (gray rectangle, 0 → 95.2)
          * L2 lower seg (red pattern 4, 95.2 → 440 with zigzag top)
          * L2 upper seg (red pattern 4, 540 → 700 with zigzag bottom)
          * \"3075.4\" label above the upper segment
    """
    ymin, ymax, ytics_spec, ylabel = y_axis_settings(rows, c)
    l1, l2_, _, _, _, total = rows[(c, "L2")]

    # Bar geometry (must match boxwidth=0.45 in the histogram block).
    bar_w  = 0.45
    bar_xl = -bar_w / 2
    bar_xr =  bar_w / 2
    # Lightning break y values.
    L1_TOP    = l1        # ~95.2
    LOWER_TOP = 440       # top of lower L2 polygon (with zigzag at this y)
    UPPER_BOT = 540       # bottom of upper L2 polygon (with zigzag at this y)
    UPPER_TOP = 700       # flat top of upper L2 polygon
    LABEL_Y   = 720
    AMP = 18              # zigzag amplitude

    # Zigzag x positions across the bar (proportions match tpch_speedup).
    z = lambda f: bar_xl + f * bar_w
    xs = [z(0.00), z(0.25), z(0.50), z(0.75), z(1.00)]
    # Y offsets for a single peak + trough wave: flat-flat-peak-trough-flat.
    y_top = [LOWER_TOP, LOWER_TOP, LOWER_TOP + AMP, LOWER_TOP - AMP, LOWER_TOP]
    y_bot = [UPPER_BOT, UPPER_BOT, UPPER_BOT + AMP, UPPER_BOT - AMP, UPPER_BOT]

    # L2 lower polygon vertices: up the left edge, zigzag across top, down right edge.
    lower_pts = []
    lower_pts.append((bar_xl, L1_TOP))
    lower_pts.append((bar_xl, LOWER_TOP))
    for px, py in zip(xs[1:], y_top[1:]):
        lower_pts.append((px, py))
    lower_pts.append((bar_xr, L1_TOP))
    lower_pts.append((bar_xl, L1_TOP))

    # L2 upper polygon: zigzag across bottom, up to flat top, back.
    upper_pts = []
    upper_pts.append((bar_xl, UPPER_BOT))
    for px, py in zip(xs[1:], y_bot[1:]):
        upper_pts.append((px, py))
    upper_pts.append((bar_xr, UPPER_TOP))
    upper_pts.append((bar_xl, UPPER_TOP))
    upper_pts.append((bar_xl, UPPER_BOT))

    def poly_str(pts):
        head = f"from {pts[0][0]:.4f},{pts[0][1]:.3f}"
        tail = " \\\n    ".join(f"to {x:.4f},{y:.3f}" for x, y in pts[1:])
        return head + " \\\n    " + tail

    plot_lines = []
    for i, (label, col, fill, colour) in enumerate(LAYER_STYLE):
        if i == 0:
            plot_lines.append(
                f"     '{dat_path.name}' using {col}:xtic(1) "
                f"title '{label}' lc rgb '{colour}' {fill} border lc rgb '{colour}'"
            )
        else:
            plot_lines.append(
                f"     ''                 using {col}             "
                f"title '{label}' lc rgb '{colour}' {fill} border lc rgb '{colour}'"
            )
    # Skip label for L2 row (its $7 == 0 in the dat file).
    label_y_off = ymax * 0.025
    plot_lines.append(
        f"     ''                 using ($0):($7>0 ? $7+{label_y_off:.3f} : 1/0):"
        f"(sprintf('%.1f', $7)) notitle "
        f"with labels center font 'Linux Libertine O,18' textcolor rgb '#202020'"
    )
    plot_clause = ", \\\n".join(plot_lines)

    script = f"""# auto-generated by plot_hierarchy_depth_size.py (lightning break)
reset
set terminal pdf size 4.2, 3.0 font 'Linux Libertine O,18'
set output '{pdf_path.name}'

set ylabel '{ylabel}' offset 1.5,0 font 'Linux Libertine O,18'
set yrange [{ymin}:{ymax}]
set ytics {ytics_spec} font 'Linux Libertine O,16'
set xtics offset 0,0.3 font 'Linux Libertine O,18'
set xtics scale 0

set key at graph 0.99, 0.99 right top vertical Left reverse \\
    samplen 1.5 spacing 1.0 width -1 \\
    font 'Linux Libertine O,14'

set style data histogram
set style histogram rowstacked
set style fill pattern border
set boxwidth 0.45
set xrange [-0.6:3.6]

set lmargin 7.0
set rmargin 0.7
set tmargin 0.6
set bmargin 2.2

set border lw 1.2 lc rgb '#0f172a'
set tics nomirror

# --- L2 bar (manually drawn — broken to keep L4/L5 bars readable) ---
# L1 segment: solid grey polygon (rectangle) 0 to {L1_TOP:.3f}.
set object 1 polygon \\
    from {bar_xl:.4f},0 to {bar_xr:.4f},0 \\
    to {bar_xr:.4f},{L1_TOP:.3f} to {bar_xl:.4f},{L1_TOP:.3f} \\
    to {bar_xl:.4f},0 \\
    fillstyle solid 1.0 fillcolor rgb '#5D5D5D' lw 1 lc rgb '#5D5D5D'

# L2 lower segment: pattern 4 red, zigzag top at y={LOWER_TOP}.
set object 2 polygon \\
    {poly_str(lower_pts)} \\
    fillstyle pattern 4 fillcolor rgb '#A84141' lw 1 lc rgb '#A84141'

# L2 upper segment: pattern 4 red, zigzag bottom at y={UPPER_BOT}, flat top at y={UPPER_TOP}.
set object 3 polygon \\
    {poly_str(upper_pts)} \\
    fillstyle pattern 4 fillcolor rgb '#A84141' lw 1 lc rgb '#A84141'

# Label showing the actual L2 variant total above the broken bar.
set label 1 "{total:.1f}" at 0,{LABEL_Y} center \\
    font 'Linux Libertine O,18' textcolor rgb '#202020'

plot \\
{plot_clause}
"""
    pdf_path.with_suffix(".gp").write_text(script)


def write_dat_with_zero_l2(rows, c, dat_path: Path):
    """Same as write_dat but L2 row has all-zero values (and zero total)
    so the histogram draws nothing at x=0 and skips the label there.
    Manual polygons handle the L2 bar instead."""
    with dat_path.open("w") as f:
        f.write("# variant\tL1\tL2\tL3\tL4\tL5\ttotal\n")
        f.write("L2\t0\t0\t0\t0\t0\t0\n")
        for v in ["L3", "L4", "L5"]:
            l1, l2, l3, l4, l5, total = rows[(c, v)]
            f.write(f"{v}\t{l1:.4f}\t{l2:.4f}\t{l3:.4f}\t{l4:.4f}\t{l5:.4f}\t{total:.4f}\n")


def main():
    rows = load_csv()
    for c, suffix in [(10, "c10_d10pct"), (2000, "c2000_d0p05pct")]:
        if not any(v == "L5" for (cc, v) in rows.keys() if cc == c):
            sys.exit(f"missing rows for c={c}")
        dat_path = HERE / f"hierarchy_depth_size_{suffix}.dat"
        pdf_path = HERE / f"hierarchy_depth_size_{suffix}.pdf"
        if c == 2000:
            # Lightning break for the towering L2 bar (3075 MB vs ~320-560).
            write_dat_with_zero_l2(rows, c, dat_path)
            write_gp_with_break(c, dat_path, pdf_path, rows)
        else:
            write_dat(rows, c, dat_path)
            write_gp(c, dat_path, pdf_path, rows)
        r = subprocess.run(
            ["gnuplot", pdf_path.with_suffix(".gp").name],
            cwd=HERE, capture_output=True, text=True)
        if r.returncode != 0:
            sys.stderr.write(r.stderr)
            sys.exit(r.returncode)
        print(f"[ok] wrote {pdf_path}")


if __name__ == "__main__":
    main()
