#!/usr/bin/env python3
"""plot_s3_density.py

Reads the S3 AND density-sweep rows from a transition_bench CSV and produces a
gnuplot PDF chart of *performance* (1 / median time, expressed as Gbit/s) vs
input density per backend.

Per-row timing is op-only:
  - CR  : pairwise A & B + to-bitset conversion of result (apples-to-apples)
  - CB  : decompressed output (ddc_compress_results = false)
  - WAH : copy + &=
  - EWAH/Concise : library fast_logicaland

Usage:  plot_s3_density.py [csv_path] [out_pdf]
Default csv: build/transition_density_sweep.csv
Default pdf: s3_density.pdf
"""
from __future__ import annotations

import csv
import re
import subprocess
import sys
from pathlib import Path

S3_TAG = re.compile(r"^S3_AND_density@d=([0-9.]+)$")

# Number of bits per bitmap = 1024 segments × 65536 bits (matches N_SEG ×
# 65536 in transition_bench.cpp).  Used to convert ms → Gbit/s:
#   throughput (Gbit/s) = NUM_BITS / (time_s · 1e9)
#                      = NUM_BITS / (time_ms · 1e-3 · 1e9)
#                      = (NUM_BITS / 1e6) / time_ms
NUM_BITS = 1024 * 65536            # 67 108 864 bits ≈ 67 Mbits per bitmap
GBITS_PER_MS = NUM_BITS / 1e6      # ≈ 67.1 — Gbit/s achieved at 1 ms-per-OR

# Backend → (display label, colour, point type, line width).
BACKENDS = [
    ("CR",              "CRoaring (pairwise+to-bitset)", "#d62728", 7,  3.0),
    ("CB-decompressed", "DDC (decompressed)",          "#1f77b4", 5,  2.4),
    ("WAH",             "WAH (FastBit)",                  "#2ca02c", 9,  1.8),
    ("EWAH",            "EWAH",                           "#9467bd", 11, 1.8),
    ("Concise",         "Concise",                        "#8c564b", 13, 1.8),
]


def parse(csv_path: Path):
    """Return dict: input-density(float) → {backend: median_ms}."""
    out: dict[float, dict[str, float]] = {}
    with csv_path.open() as f:
        for row in csv.DictReader(f):
            m = S3_TAG.match(row["scenario"])
            if not m:
                continue
            d = float(m.group(1))
            out.setdefault(d, {})[row["backend"]] = float(row["median_ms"])
    return out


def write_wide(samples: dict, dat_path: Path):
    """Write density-major TSV: column 1 = d_in,
    columns 2..6 = throughput (Gbit/s) for each backend."""
    with dat_path.open("w") as f:
        f.write("# d_in\t" + "\t".join(b[0] for b in BACKENDS) + "\n")
        for d in sorted(samples.keys()):
            row = [f"{d:.5f}"]
            for be, *_ in BACKENDS:
                ms = samples[d].get(be)
                if ms is None or ms <= 0:
                    row.append("?")
                else:
                    row.append(f"{GBITS_PER_MS / ms:.4f}")
            f.write("\t".join(row) + "\n")


def write_gnuplot(gp_path: Path, dat_path: Path, pdf_path: Path):
    """Emit a self-contained gnuplot PDF script."""
    plots = []
    for i, (col_name, label, colour, pt, lw) in enumerate(BACKENDS, start=2):
        plots.append(
            f"  '{dat_path.name}' using 1:{i} with linespoints "
            f"lw {lw} pt {pt} ps 0.9 lc rgb '{colour}' title '{label}'"
        )
    plot_clause = ", \\\n".join(plots)

    # Two CR regime boundaries on the AND chart (x = d_in):
    #   input array→bitset at count_a = 4096   ⇒  d_in = 0.0625
    #   result array→bitset at count_a ≈ 16384 ⇒  d_in = 0.25  (expected; the
    #       exact crossover depends on the random A,B but the threshold is
    #       4096/65536 for result_card → d_in_at_threshold = √(4096/65536) = 0.25)
    script = f"""# auto-generated by plot_s3_density.py
set terminal pdfcairo size 9in,5.5in enhanced font 'DejaVu Sans,11'
set output '{pdf_path.name}'

set title "AND op-only: performance vs input density\\n{{/*0.85 (independent random A and B, 1024 × 65536-bit segments; CR includes pairwise + to-bitset)}}" font ',13'
set xlabel "input density  d_in = count_a / 65 536  (= 1 / cardinality)"
set ylabel "performance  (Gbit/s, 67 Mbits ÷ median AND time)"

set logscale x 10
set xrange [0.0005:0.85]
set yrange [0:*]
set format x '%.4f'

set grid back lc rgb '#cccccc'
set key outside right top vertical Left reverse samplen 2

# CR regime boundaries.
trigger_input_bitset  = {4096 / 65536.0}         # 0.0625 — c=16
trigger_result_bitset = {(4096 / 65536.0)**0.5}  # 0.25   — c=4 (≈ where X²/65536 > 4096)

set arrow from trigger_input_bitset,graph 0 to trigger_input_bitset,graph 1 nohead \\
    lw 1 dt 2 lc rgb '#444444'
set arrow from trigger_result_bitset,graph 0 to trigger_result_bitset,graph 1 nohead \\
    lw 1 dt 3 lc rgb '#888888'

set label "CR inputs become\\nbitset (count_a > 4096)" \\
    at trigger_input_bitset,graph 0.92 right offset -0.6,0 \\
    tc rgb '#333333' font ',9'
set label "CR result becomes\\nbitset (no extract back)" \\
    at trigger_result_bitset,graph 0.42 left offset 0.6,0 \\
    tc rgb '#666666' font ',9'

plot \\
{plot_clause}
"""
    gp_path.write_text(script)


def main():
    csv_path = Path(sys.argv[1] if len(sys.argv) > 1 else "build/transition_density_sweep.csv")
    out_pdf  = Path(sys.argv[2] if len(sys.argv) > 2 else "s3_density.pdf")

    if not csv_path.exists():
        sys.exit(f"error: {csv_path} not found")

    samples = parse(csv_path)
    if not samples:
        sys.exit(f"error: no S3_AND_density@d=... rows in {csv_path}")

    print(f"[parse] {len(samples)} density points")
    for d in sorted(samples.keys()):
        be_count = len(samples[d])
        print(f"  d_in={d:.5f}  ({be_count} backends)")

    dat_path = out_pdf.with_suffix('.dat')
    gp_path  = out_pdf.with_suffix('.gp')
    write_wide(samples, dat_path)
    write_gnuplot(gp_path, dat_path, out_pdf)
    print(f"[write] {dat_path}")
    print(f"[write] {gp_path}")

    workdir = out_pdf.parent if out_pdf.parent.as_posix() else Path(".")
    r = subprocess.run(["gnuplot", gp_path.name], cwd=workdir,
                       capture_output=True, text=True)
    if r.returncode != 0:
        print("[gnuplot stderr]", r.stderr, file=sys.stderr)
        sys.exit(r.returncode)
    print(f"[ok]   wrote {out_pdf}")


if __name__ == "__main__":
    main()
