#!/usr/bin/env python3
"""plot_and_cliff.py — CRoaring bitset→array transition cliff PDF.

Reads build/unified_results.csv (output of benchmark_app on the
bm_100m_t<count_a>_<algo>/ directories — independent random bitmaps,
AND result is non-trivial).  Emits a focused PDF showing each backend
across the count_a range that exposes CR's bitset→array extract cliff.

Convention: solid lines, distinct colours, distinct markers.  No
dashed lines.

x-axis: count_a per 65 536-segment (linear).  The transition cliff
        sits around count_a = 16384.
y-axis: performance (Gbit/s) = 100 Mbits ÷ median AND time.

Usage:  plot_and_cliff.py [csv] [out_pdf]
"""
from __future__ import annotations

import csv
import subprocess
import sys
from pathlib import Path

NUM_BITS = 100_000_000
GBITS_PER_MS = NUM_BITS / 1e6        # = 100.0

C_MIN = 4500
C_MAX = 24000

BACKENDS = [
    ("DDC (New)",     "DDC",             "#1f4ed8", 7,  3.2),
    ("CRoaring",         "CRoaring",           "#dc2626", 5,  2.6),
    ("Bitset (AVX512)",  "Bitset (AVX-512)",   "#0891b2", 9,  2.2),
    ("Bitset (Plain)",   "Bitset (scalar)",    "#7c3aed", 11, 2.2),
    ("WAH (FastBit)",    "WAH (FastBit)",      "#16a34a", 13, 2.0),
    ("EWAH",             "EWAH",               "#ea580c", 4,  2.0),
    ("Concise",          "Concise",            "#92400e", 15, 2.0),
]

# Standard sweep cardinalities — exclude from cliff chart even when they
# overlap the count_a range (e.g. c=8000 disjoint vs t=8000 independent).
STANDARD_CS = {2, 5, 10, 20, 50, 100, 200, 300, 500, 1000,
               2000, 3000, 4000, 5000, 8000, 10000, 20000, 50000}


def load(csv_path: Path):
    """{count_a: {backend: median_ms}} for transition rows in [C_MIN, C_MAX]."""
    out: dict[int, dict[str, float]] = {}
    with csv_path.open() as f:
        for row in csv.DictReader(f):
            if int(row["num_rows"]) != NUM_BITS:
                continue
            if row["operation"] != "AND_op":
                continue
            c = int(row["cardinality"])
            if c < C_MIN or c > C_MAX:
                continue
            # Disambiguate dirs whose cardinality field collides between
            # _c<N>_ (standard, result_card=0) and _t<N>_ (transition,
            # result_card>0).  Keep the transition row.
            if c in STANDARD_CS and int(row["result_cardinality"]) == 0:
                continue
            out.setdefault(c, {})[row["backend"]] = float(row["time_ms"])
    return out


def write_dat(samples, dat_path: Path):
    cs = sorted(samples.keys())
    with dat_path.open("w") as f:
        f.write("# count_a\t" + "\t".join(b[0] for b in BACKENDS) + "\n")
        for c in cs:
            row = [str(c)]
            for be, *_ in BACKENDS:
                ms = samples[c].get(be)
                row.append(f"{GBITS_PER_MS / ms:.4f}" if ms and ms > 0 else "?")
            f.write("\t".join(row) + "\n")


def write_gp(gp_path: Path, dat_path: Path, pdf_path: Path):
    plots = []
    for col, (_, label, colour, pt, lw) in enumerate(BACKENDS, start=2):
        plots.append(
            f"  '{dat_path.name}' using 1:{col} with linespoints "
            f"lw {lw} pt {pt} ps 1.1 lc rgb '{colour}' title '{label}'"
        )
    plot_clause = ", \\\n".join(plots)

    threshold = 16384  # count_a above which AND result spills past 4096/segment
                       # and CR keeps the bitset (no more bitset→array extract).

    script = f"""# auto-generated by plot_and_cliff.py
set terminal pdfcairo size 10in,6in enhanced font 'DejaVu Sans,11'
set output '{pdf_path.name}'

set title "CRoaring bitset→array AND cliff — performance vs density\\n{{/*0.85 (100 M rows; independent random A, B with count\\\\_a set bits per 65 536-segment)}}" font ',13'
set xlabel "count\\\\_a  (bits per 65 536-bit segment)   →   density = count\\\\_a / 65 536"
set ylabel "performance  (Gbit/s, 100 Mbits ÷ median AND time)"

set xrange [{C_MIN - 500}:{C_MAX + 1000}]
set xtics 4000, 2000, 24000
set mxtics 2

# Highlight the cliff threshold (count_a above which CR result_card spills
# past 4096/segment and CR stops paying the bitset→array extract cost).
set arrow from {threshold},graph 0 to {threshold},graph 1 nohead \\
    lw 1.2 lc rgb '#94a3b8'
set label "count_a = √(4096·65536) = 16 384" \\
    at {threshold},graph 0.45 right offset -0.6,0 \\
    tc rgb '#475569' font ',9'
set label "(CR cliff: result stays bitset above here →\\n no more bitset→array extract)" \\
    at {threshold},graph 0.36 right offset -0.6,0 \\
    tc rgb '#94a3b8' font ',8'

set yrange [0:*]
set grid back lc rgb '#cbd5e1' lw 0.6
set border lw 1.2 lc rgb '#0f172a'
set key outside right top vertical Left reverse samplen 2.6 spacing 1.2 font ',10'

plot \\
{plot_clause}
"""
    gp_path.write_text(script)


def main():
    csv_path = Path(sys.argv[1] if len(sys.argv) > 1 else "build/unified_results.csv")
    out_pdf  = Path(sys.argv[2] if len(sys.argv) > 2 else "and_cliff.pdf")

    if not csv_path.exists():
        sys.exit(f"error: {csv_path} not found")
    samples = load(csv_path)
    if not samples:
        sys.exit("error: no transition AND_op rows in range")

    cs = sorted(samples.keys())
    print(f"[load] {len(cs)} count_a points: {cs}")

    dat_path = out_pdf.with_suffix('.dat')
    gp_path  = out_pdf.with_suffix('.gp')
    write_dat(samples, dat_path)
    write_gp(gp_path, dat_path, out_pdf)
    print(f"[write] {dat_path}\n[write] {gp_path}")

    workdir = out_pdf.parent if out_pdf.parent.as_posix() else Path(".")
    r = subprocess.run(["gnuplot", gp_path.name], cwd=workdir,
                       capture_output=True, text=True)
    if r.returncode != 0:
        print("[gnuplot stderr]", r.stderr, file=sys.stderr)
        sys.exit(r.returncode)
    print(f"[ok]   wrote {out_pdf}")


if __name__ == "__main__":
    main()
